### ISSUE TITLE
name[casing] processor breaks handlers

### ISSUE THREAD

**Issue by sjmonson** [scrufulufugus/ansible-lint-resolver#1]
# Description

The `name[casing]` processor is not smart enough to update `notify` keywords. Thus, when a handler's name is capitalized the notify call breaks.

## Example

```yaml
---
- name: Broken notify
  tasks:
    - name: Call handler
      ansible.builtin.debug:
        msg: "Call handler"
      notify: my handler # <- Not capitalized

  handlers:
    - name: My handler
      ansible.builtin.debug:
        msg: "My handler"
```

Also keep in mind the case of:
```yaml
---
- name: Broken notify
  tasks:
    - name: Call handler
      ansible.builtin.debug:
        msg: "Call handler"
      notify: my handler # <- Works cause `listen`

  handlers:
    - name: My handler
      ansible.builtin.debug:
        msg: "My handler"
      listen: "my handler" # <- listen
```
